---
abstract: 'RT IR Extension'
author:
  - 'Best Practical Solutions <sales@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-IR
no_index:
  directory:
    - etc
    - html
    - inc
    - po
    - t
requires:
  Business::Hours: 0
  Business::SLA: 0
  DBIx::SearchBuilder: 1.51
  Hook::LexWrap: 0
  Net::CIDR: 0
  Net::Whois::RIPE: 0
  Regexp::Common: 0
  Regexp::Common::net::CIDR: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 2.6.2rc1
